### ISSUE TITLE
 Can't find variable: __requireContext

### ISSUE THREAD

**Issue by devthejo** [asapach/babel-plugin-transform-require-context#1]
Hello,

I have this bug with RN 0.56:

Can't find variable: __requireContext

Thanks

**Comment by asapach** [comment]
Could you please provide an example of the file you're trying to transpile? I assume RN stands for React Native?

**Comment by devthejo** [comment]
yep RN is for React Native

`
const containers = require.context('./containers', true, /\.js$/)

export default containers
`

**Comment by asapach** [comment]
OK I tried transpiling your code using the following config: 
`{ presets: ['react-native'], plugins: ['transform-require-context] }`

Input:
```js
const containers = require.context('./containers', true, /.js$/)
export default containers
```

Output:
```js
Object.defineProperty(exports,"__esModule",{value:true});
var containers=function(){
  function req(){}
  req.keys=function(){return[];};
  req.resolve=function(){};
  return req;
}();
exports.default=containers;
```

I don't see any mention of `__requireContext`. Do you have an error stack trace to point where it's coming from?

**Comment by devthejo** [comment]
OK thank you, sorry, my bad, I was confusing with https://github.com/smrq/babel-plugin-require-context-hook
